version: '2.20.3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3001:3000
    restart: always
  nodered:
    image: nodered/node-red
    container_name: node-red
    ports:
      - 1880:1880
    volumes:
      - ./node-red/persistence/data:/data
    restart: always
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 8080:8080
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
